# Generated by Django 2.2.3 on 2023-09-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='cart_id',
            new_name='card_id',
        ),
    ]
